[book]
authors = ["takejohn"]
language = "ja"
multilingual = false
src = "src"
title = "AiScript Docs"

[output.html]
additional-css = ["theme/css/language-picker.css"]
additional-js = ["bundle/dist/main.js"]

[build]
extra-watch-dirs = ["po"]

[preprocessor.gettext]
after = ["links"]
